---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by davidlakubu.
--- DateTime: 05/04/2023 08:12
---

function RouteHandler(params)
    local name = "No name"
    print("-- Hello  from [hello] middleware !")
    return continue()
end