---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by davidlakubu.
--- DateTime: 03/04/2023 19:09
---
--json = require("json")

function GET()
    return "<html><head><title>Try a post</title></head><body>Try using a post request</body></html>",200
end
function POST()
    return jsonify({req=request}),200
end