---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by davidlakubu.
--- DateTime: 03/04/2023 12:18
---

api_query = {}

function api_query.GET()
    print(request)
    return jsonify(request)
end