---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by davidlakubu.
--- DateTime: 03/05/2023 11:30
---

function GET()
    --[[ print(jsonify(request))

    ]]
    local _path = request.route.subPath

    return renderTemplate("html/404.html", { p = _path }), 200
end