---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by davidlakubu.
--- DateTime: 03/05/2023 11:30
---

function GET()
    print(jsonify(request))
    return jsonify({message="Hello from catch all"}), 200
end